max_width = 120
newline_style = "Unix"
chain_width = 120
fn_call_width = 120

hard_tabs = true
tab_spaces = 2

# unstable_features = true
# blank_lines_upper_bound = 2
# format_code_in_doc_comments = true
# imports_layout = "HorizontalVertical"
# control_brace_style = "ClosingNextLine"
# match_block_trailing_comma = true
# report_fixme = "Always"
# report_todo = "Unnumbered"
